project:
  type: website

website:
  title: "R Fundamentals"
  navbar:
    left:
      - href: about.qmd
        text: Acerca de

      - href: index.qmd
        text: Guía de estudio

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - estructuras.qmd
          - funciones.qmd
      - section: "Dataset"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

